# Browser Parameters
delay_secs_short: 1  # seconds to wait between actions
delay_secs_long: 1 # seconds to wait between long actions
max_minutes_wait: 5 # maximum minutes to wait before checking for appointments
headless: true # run browser in headless mode

# Telegram
chat_id: YOUR_TELEGRAM_CHAT_ID
api_key: 'YOUR_TELEGRAM_BOT_API_KEY'

# Maccabi
user_id: 'YOUR_MACCABI_USER_ID'
password: 'YOUR_MACCABI_PASSWORD'

# Appointment Details
patient_name: 'PATIENT_NAME'
patient_id: 'PATIENT_ID_NUMBER'
doctor_name: 'DOCTOR_NAME'
only_before: '01/01/26'  # only notify if available appointment is before this date (DD/MM/YY)

